
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `training_menus` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model training_menus
 * 
 */
export type training_menusModel = runtime.Types.Result.DefaultSelection<Prisma.$training_menusPayload>

export type AggregateTraining_menus = {
  _count: Training_menusCountAggregateOutputType | null
  _avg: Training_menusAvgAggregateOutputType | null
  _sum: Training_menusSumAggregateOutputType | null
  _min: Training_menusMinAggregateOutputType | null
  _max: Training_menusMaxAggregateOutputType | null
}

export type Training_menusAvgAggregateOutputType = {
  id: number | null
}

export type Training_menusSumAggregateOutputType = {
  id: number | null
}

export type Training_menusMinAggregateOutputType = {
  id: number | null
  name: string | null
  created_at: Date | null
}

export type Training_menusMaxAggregateOutputType = {
  id: number | null
  name: string | null
  created_at: Date | null
}

export type Training_menusCountAggregateOutputType = {
  id: number
  name: number
  exercises: number
  created_at: number
  _all: number
}


export type Training_menusAvgAggregateInputType = {
  id?: true
}

export type Training_menusSumAggregateInputType = {
  id?: true
}

export type Training_menusMinAggregateInputType = {
  id?: true
  name?: true
  created_at?: true
}

export type Training_menusMaxAggregateInputType = {
  id?: true
  name?: true
  created_at?: true
}

export type Training_menusCountAggregateInputType = {
  id?: true
  name?: true
  exercises?: true
  created_at?: true
  _all?: true
}

export type Training_menusAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which training_menus to aggregate.
   */
  where?: Prisma.training_menusWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of training_menus to fetch.
   */
  orderBy?: Prisma.training_menusOrderByWithRelationInput | Prisma.training_menusOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.training_menusWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` training_menus from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` training_menus.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned training_menus
  **/
  _count?: true | Training_menusCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: Training_menusAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: Training_menusSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Training_menusMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Training_menusMaxAggregateInputType
}

export type GetTraining_menusAggregateType<T extends Training_menusAggregateArgs> = {
      [P in keyof T & keyof AggregateTraining_menus]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTraining_menus[P]>
    : Prisma.GetScalarType<T[P], AggregateTraining_menus[P]>
}




export type training_menusGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.training_menusWhereInput
  orderBy?: Prisma.training_menusOrderByWithAggregationInput | Prisma.training_menusOrderByWithAggregationInput[]
  by: Prisma.Training_menusScalarFieldEnum[] | Prisma.Training_menusScalarFieldEnum
  having?: Prisma.training_menusScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Training_menusCountAggregateInputType | true
  _avg?: Training_menusAvgAggregateInputType
  _sum?: Training_menusSumAggregateInputType
  _min?: Training_menusMinAggregateInputType
  _max?: Training_menusMaxAggregateInputType
}

export type Training_menusGroupByOutputType = {
  id: number
  name: string | null
  exercises: runtime.JsonValue | null
  created_at: Date | null
  _count: Training_menusCountAggregateOutputType | null
  _avg: Training_menusAvgAggregateOutputType | null
  _sum: Training_menusSumAggregateOutputType | null
  _min: Training_menusMinAggregateOutputType | null
  _max: Training_menusMaxAggregateOutputType | null
}

type GetTraining_menusGroupByPayload<T extends training_menusGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Training_menusGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Training_menusGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Training_menusGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Training_menusGroupByOutputType[P]>
      }
    >
  >



export type training_menusWhereInput = {
  AND?: Prisma.training_menusWhereInput | Prisma.training_menusWhereInput[]
  OR?: Prisma.training_menusWhereInput[]
  NOT?: Prisma.training_menusWhereInput | Prisma.training_menusWhereInput[]
  id?: Prisma.IntFilter<"training_menus"> | number
  name?: Prisma.StringNullableFilter<"training_menus"> | string | null
  exercises?: Prisma.JsonNullableFilter<"training_menus">
  created_at?: Prisma.DateTimeNullableFilter<"training_menus"> | Date | string | null
  user_recaps?: Prisma.User_recapsListRelationFilter
}

export type training_menusOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrderInput | Prisma.SortOrder
  exercises?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrderInput | Prisma.SortOrder
  user_recaps?: Prisma.user_recapsOrderByRelationAggregateInput
}

export type training_menusWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.training_menusWhereInput | Prisma.training_menusWhereInput[]
  OR?: Prisma.training_menusWhereInput[]
  NOT?: Prisma.training_menusWhereInput | Prisma.training_menusWhereInput[]
  name?: Prisma.StringNullableFilter<"training_menus"> | string | null
  exercises?: Prisma.JsonNullableFilter<"training_menus">
  created_at?: Prisma.DateTimeNullableFilter<"training_menus"> | Date | string | null
  user_recaps?: Prisma.User_recapsListRelationFilter
}, "id">

export type training_menusOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrderInput | Prisma.SortOrder
  exercises?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.training_menusCountOrderByAggregateInput
  _avg?: Prisma.training_menusAvgOrderByAggregateInput
  _max?: Prisma.training_menusMaxOrderByAggregateInput
  _min?: Prisma.training_menusMinOrderByAggregateInput
  _sum?: Prisma.training_menusSumOrderByAggregateInput
}

export type training_menusScalarWhereWithAggregatesInput = {
  AND?: Prisma.training_menusScalarWhereWithAggregatesInput | Prisma.training_menusScalarWhereWithAggregatesInput[]
  OR?: Prisma.training_menusScalarWhereWithAggregatesInput[]
  NOT?: Prisma.training_menusScalarWhereWithAggregatesInput | Prisma.training_menusScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"training_menus"> | number
  name?: Prisma.StringNullableWithAggregatesFilter<"training_menus"> | string | null
  exercises?: Prisma.JsonNullableWithAggregatesFilter<"training_menus">
  created_at?: Prisma.DateTimeNullableWithAggregatesFilter<"training_menus"> | Date | string | null
}

export type training_menusCreateInput = {
  name?: string | null
  exercises?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  created_at?: Date | string | null
  user_recaps?: Prisma.user_recapsCreateNestedManyWithoutTraining_menusInput
}

export type training_menusUncheckedCreateInput = {
  id?: number
  name?: string | null
  exercises?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  created_at?: Date | string | null
  user_recaps?: Prisma.user_recapsUncheckedCreateNestedManyWithoutTraining_menusInput
}

export type training_menusUpdateInput = {
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  exercises?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  user_recaps?: Prisma.user_recapsUpdateManyWithoutTraining_menusNestedInput
}

export type training_menusUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  exercises?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  user_recaps?: Prisma.user_recapsUncheckedUpdateManyWithoutTraining_menusNestedInput
}

export type training_menusCreateManyInput = {
  id?: number
  name?: string | null
  exercises?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  created_at?: Date | string | null
}

export type training_menusUpdateManyMutationInput = {
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  exercises?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type training_menusUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  exercises?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type training_menusCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  exercises?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type training_menusAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type training_menusMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type training_menusMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type training_menusSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type Training_menusNullableScalarRelationFilter = {
  is?: Prisma.training_menusWhereInput | null
  isNot?: Prisma.training_menusWhereInput | null
}

export type training_menusCreateNestedOneWithoutUser_recapsInput = {
  create?: Prisma.XOR<Prisma.training_menusCreateWithoutUser_recapsInput, Prisma.training_menusUncheckedCreateWithoutUser_recapsInput>
  connectOrCreate?: Prisma.training_menusCreateOrConnectWithoutUser_recapsInput
  connect?: Prisma.training_menusWhereUniqueInput
}

export type training_menusUpdateOneWithoutUser_recapsNestedInput = {
  create?: Prisma.XOR<Prisma.training_menusCreateWithoutUser_recapsInput, Prisma.training_menusUncheckedCreateWithoutUser_recapsInput>
  connectOrCreate?: Prisma.training_menusCreateOrConnectWithoutUser_recapsInput
  upsert?: Prisma.training_menusUpsertWithoutUser_recapsInput
  disconnect?: Prisma.training_menusWhereInput | boolean
  delete?: Prisma.training_menusWhereInput | boolean
  connect?: Prisma.training_menusWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.training_menusUpdateToOneWithWhereWithoutUser_recapsInput, Prisma.training_menusUpdateWithoutUser_recapsInput>, Prisma.training_menusUncheckedUpdateWithoutUser_recapsInput>
}

export type training_menusCreateWithoutUser_recapsInput = {
  name?: string | null
  exercises?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  created_at?: Date | string | null
}

export type training_menusUncheckedCreateWithoutUser_recapsInput = {
  id?: number
  name?: string | null
  exercises?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  created_at?: Date | string | null
}

export type training_menusCreateOrConnectWithoutUser_recapsInput = {
  where: Prisma.training_menusWhereUniqueInput
  create: Prisma.XOR<Prisma.training_menusCreateWithoutUser_recapsInput, Prisma.training_menusUncheckedCreateWithoutUser_recapsInput>
}

export type training_menusUpsertWithoutUser_recapsInput = {
  update: Prisma.XOR<Prisma.training_menusUpdateWithoutUser_recapsInput, Prisma.training_menusUncheckedUpdateWithoutUser_recapsInput>
  create: Prisma.XOR<Prisma.training_menusCreateWithoutUser_recapsInput, Prisma.training_menusUncheckedCreateWithoutUser_recapsInput>
  where?: Prisma.training_menusWhereInput
}

export type training_menusUpdateToOneWithWhereWithoutUser_recapsInput = {
  where?: Prisma.training_menusWhereInput
  data: Prisma.XOR<Prisma.training_menusUpdateWithoutUser_recapsInput, Prisma.training_menusUncheckedUpdateWithoutUser_recapsInput>
}

export type training_menusUpdateWithoutUser_recapsInput = {
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  exercises?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type training_menusUncheckedUpdateWithoutUser_recapsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  exercises?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}


/**
 * Count Type Training_menusCountOutputType
 */

export type Training_menusCountOutputType = {
  user_recaps: number
}

export type Training_menusCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user_recaps?: boolean | Training_menusCountOutputTypeCountUser_recapsArgs
}

/**
 * Training_menusCountOutputType without action
 */
export type Training_menusCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Training_menusCountOutputType
   */
  select?: Prisma.Training_menusCountOutputTypeSelect<ExtArgs> | null
}

/**
 * Training_menusCountOutputType without action
 */
export type Training_menusCountOutputTypeCountUser_recapsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.user_recapsWhereInput
}


export type training_menusSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  exercises?: boolean
  created_at?: boolean
  user_recaps?: boolean | Prisma.training_menus$user_recapsArgs<ExtArgs>
  _count?: boolean | Prisma.Training_menusCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["training_menus"]>

export type training_menusSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  exercises?: boolean
  created_at?: boolean
}, ExtArgs["result"]["training_menus"]>

export type training_menusSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  exercises?: boolean
  created_at?: boolean
}, ExtArgs["result"]["training_menus"]>

export type training_menusSelectScalar = {
  id?: boolean
  name?: boolean
  exercises?: boolean
  created_at?: boolean
}

export type training_menusOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "exercises" | "created_at", ExtArgs["result"]["training_menus"]>
export type training_menusInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user_recaps?: boolean | Prisma.training_menus$user_recapsArgs<ExtArgs>
  _count?: boolean | Prisma.Training_menusCountOutputTypeDefaultArgs<ExtArgs>
}
export type training_menusIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type training_menusIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $training_menusPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "training_menus"
  objects: {
    user_recaps: Prisma.$user_recapsPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    name: string | null
    exercises: runtime.JsonValue | null
    created_at: Date | null
  }, ExtArgs["result"]["training_menus"]>
  composites: {}
}

export type training_menusGetPayload<S extends boolean | null | undefined | training_menusDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$training_menusPayload, S>

export type training_menusCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<training_menusFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Training_menusCountAggregateInputType | true
  }

export interface training_menusDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['training_menus'], meta: { name: 'training_menus' } }
  /**
   * Find zero or one Training_menus that matches the filter.
   * @param {training_menusFindUniqueArgs} args - Arguments to find a Training_menus
   * @example
   * // Get one Training_menus
   * const training_menus = await prisma.training_menus.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends training_menusFindUniqueArgs>(args: Prisma.SelectSubset<T, training_menusFindUniqueArgs<ExtArgs>>): Prisma.Prisma__training_menusClient<runtime.Types.Result.GetResult<Prisma.$training_menusPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Training_menus that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {training_menusFindUniqueOrThrowArgs} args - Arguments to find a Training_menus
   * @example
   * // Get one Training_menus
   * const training_menus = await prisma.training_menus.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends training_menusFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, training_menusFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__training_menusClient<runtime.Types.Result.GetResult<Prisma.$training_menusPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Training_menus that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {training_menusFindFirstArgs} args - Arguments to find a Training_menus
   * @example
   * // Get one Training_menus
   * const training_menus = await prisma.training_menus.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends training_menusFindFirstArgs>(args?: Prisma.SelectSubset<T, training_menusFindFirstArgs<ExtArgs>>): Prisma.Prisma__training_menusClient<runtime.Types.Result.GetResult<Prisma.$training_menusPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Training_menus that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {training_menusFindFirstOrThrowArgs} args - Arguments to find a Training_menus
   * @example
   * // Get one Training_menus
   * const training_menus = await prisma.training_menus.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends training_menusFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, training_menusFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__training_menusClient<runtime.Types.Result.GetResult<Prisma.$training_menusPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Training_menus that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {training_menusFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Training_menus
   * const training_menus = await prisma.training_menus.findMany()
   * 
   * // Get first 10 Training_menus
   * const training_menus = await prisma.training_menus.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const training_menusWithIdOnly = await prisma.training_menus.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends training_menusFindManyArgs>(args?: Prisma.SelectSubset<T, training_menusFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$training_menusPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Training_menus.
   * @param {training_menusCreateArgs} args - Arguments to create a Training_menus.
   * @example
   * // Create one Training_menus
   * const Training_menus = await prisma.training_menus.create({
   *   data: {
   *     // ... data to create a Training_menus
   *   }
   * })
   * 
   */
  create<T extends training_menusCreateArgs>(args: Prisma.SelectSubset<T, training_menusCreateArgs<ExtArgs>>): Prisma.Prisma__training_menusClient<runtime.Types.Result.GetResult<Prisma.$training_menusPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Training_menus.
   * @param {training_menusCreateManyArgs} args - Arguments to create many Training_menus.
   * @example
   * // Create many Training_menus
   * const training_menus = await prisma.training_menus.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends training_menusCreateManyArgs>(args?: Prisma.SelectSubset<T, training_menusCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Training_menus and returns the data saved in the database.
   * @param {training_menusCreateManyAndReturnArgs} args - Arguments to create many Training_menus.
   * @example
   * // Create many Training_menus
   * const training_menus = await prisma.training_menus.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Training_menus and only return the `id`
   * const training_menusWithIdOnly = await prisma.training_menus.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends training_menusCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, training_menusCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$training_menusPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Training_menus.
   * @param {training_menusDeleteArgs} args - Arguments to delete one Training_menus.
   * @example
   * // Delete one Training_menus
   * const Training_menus = await prisma.training_menus.delete({
   *   where: {
   *     // ... filter to delete one Training_menus
   *   }
   * })
   * 
   */
  delete<T extends training_menusDeleteArgs>(args: Prisma.SelectSubset<T, training_menusDeleteArgs<ExtArgs>>): Prisma.Prisma__training_menusClient<runtime.Types.Result.GetResult<Prisma.$training_menusPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Training_menus.
   * @param {training_menusUpdateArgs} args - Arguments to update one Training_menus.
   * @example
   * // Update one Training_menus
   * const training_menus = await prisma.training_menus.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends training_menusUpdateArgs>(args: Prisma.SelectSubset<T, training_menusUpdateArgs<ExtArgs>>): Prisma.Prisma__training_menusClient<runtime.Types.Result.GetResult<Prisma.$training_menusPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Training_menus.
   * @param {training_menusDeleteManyArgs} args - Arguments to filter Training_menus to delete.
   * @example
   * // Delete a few Training_menus
   * const { count } = await prisma.training_menus.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends training_menusDeleteManyArgs>(args?: Prisma.SelectSubset<T, training_menusDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Training_menus.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {training_menusUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Training_menus
   * const training_menus = await prisma.training_menus.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends training_menusUpdateManyArgs>(args: Prisma.SelectSubset<T, training_menusUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Training_menus and returns the data updated in the database.
   * @param {training_menusUpdateManyAndReturnArgs} args - Arguments to update many Training_menus.
   * @example
   * // Update many Training_menus
   * const training_menus = await prisma.training_menus.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Training_menus and only return the `id`
   * const training_menusWithIdOnly = await prisma.training_menus.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends training_menusUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, training_menusUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$training_menusPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Training_menus.
   * @param {training_menusUpsertArgs} args - Arguments to update or create a Training_menus.
   * @example
   * // Update or create a Training_menus
   * const training_menus = await prisma.training_menus.upsert({
   *   create: {
   *     // ... data to create a Training_menus
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Training_menus we want to update
   *   }
   * })
   */
  upsert<T extends training_menusUpsertArgs>(args: Prisma.SelectSubset<T, training_menusUpsertArgs<ExtArgs>>): Prisma.Prisma__training_menusClient<runtime.Types.Result.GetResult<Prisma.$training_menusPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Training_menus.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {training_menusCountArgs} args - Arguments to filter Training_menus to count.
   * @example
   * // Count the number of Training_menus
   * const count = await prisma.training_menus.count({
   *   where: {
   *     // ... the filter for the Training_menus we want to count
   *   }
   * })
  **/
  count<T extends training_menusCountArgs>(
    args?: Prisma.Subset<T, training_menusCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Training_menusCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Training_menus.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Training_menusAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Training_menusAggregateArgs>(args: Prisma.Subset<T, Training_menusAggregateArgs>): Prisma.PrismaPromise<GetTraining_menusAggregateType<T>>

  /**
   * Group by Training_menus.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {training_menusGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends training_menusGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: training_menusGroupByArgs['orderBy'] }
      : { orderBy?: training_menusGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, training_menusGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTraining_menusGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the training_menus model
 */
readonly fields: training_menusFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for training_menus.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__training_menusClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user_recaps<T extends Prisma.training_menus$user_recapsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.training_menus$user_recapsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$user_recapsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the training_menus model
 */
export interface training_menusFieldRefs {
  readonly id: Prisma.FieldRef<"training_menus", 'Int'>
  readonly name: Prisma.FieldRef<"training_menus", 'String'>
  readonly exercises: Prisma.FieldRef<"training_menus", 'Json'>
  readonly created_at: Prisma.FieldRef<"training_menus", 'DateTime'>
}
    

// Custom InputTypes
/**
 * training_menus findUnique
 */
export type training_menusFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the training_menus
   */
  select?: Prisma.training_menusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the training_menus
   */
  omit?: Prisma.training_menusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.training_menusInclude<ExtArgs> | null
  /**
   * Filter, which training_menus to fetch.
   */
  where: Prisma.training_menusWhereUniqueInput
}

/**
 * training_menus findUniqueOrThrow
 */
export type training_menusFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the training_menus
   */
  select?: Prisma.training_menusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the training_menus
   */
  omit?: Prisma.training_menusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.training_menusInclude<ExtArgs> | null
  /**
   * Filter, which training_menus to fetch.
   */
  where: Prisma.training_menusWhereUniqueInput
}

/**
 * training_menus findFirst
 */
export type training_menusFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the training_menus
   */
  select?: Prisma.training_menusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the training_menus
   */
  omit?: Prisma.training_menusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.training_menusInclude<ExtArgs> | null
  /**
   * Filter, which training_menus to fetch.
   */
  where?: Prisma.training_menusWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of training_menus to fetch.
   */
  orderBy?: Prisma.training_menusOrderByWithRelationInput | Prisma.training_menusOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for training_menus.
   */
  cursor?: Prisma.training_menusWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` training_menus from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` training_menus.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of training_menus.
   */
  distinct?: Prisma.Training_menusScalarFieldEnum | Prisma.Training_menusScalarFieldEnum[]
}

/**
 * training_menus findFirstOrThrow
 */
export type training_menusFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the training_menus
   */
  select?: Prisma.training_menusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the training_menus
   */
  omit?: Prisma.training_menusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.training_menusInclude<ExtArgs> | null
  /**
   * Filter, which training_menus to fetch.
   */
  where?: Prisma.training_menusWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of training_menus to fetch.
   */
  orderBy?: Prisma.training_menusOrderByWithRelationInput | Prisma.training_menusOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for training_menus.
   */
  cursor?: Prisma.training_menusWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` training_menus from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` training_menus.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of training_menus.
   */
  distinct?: Prisma.Training_menusScalarFieldEnum | Prisma.Training_menusScalarFieldEnum[]
}

/**
 * training_menus findMany
 */
export type training_menusFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the training_menus
   */
  select?: Prisma.training_menusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the training_menus
   */
  omit?: Prisma.training_menusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.training_menusInclude<ExtArgs> | null
  /**
   * Filter, which training_menus to fetch.
   */
  where?: Prisma.training_menusWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of training_menus to fetch.
   */
  orderBy?: Prisma.training_menusOrderByWithRelationInput | Prisma.training_menusOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing training_menus.
   */
  cursor?: Prisma.training_menusWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` training_menus from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` training_menus.
   */
  skip?: number
  distinct?: Prisma.Training_menusScalarFieldEnum | Prisma.Training_menusScalarFieldEnum[]
}

/**
 * training_menus create
 */
export type training_menusCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the training_menus
   */
  select?: Prisma.training_menusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the training_menus
   */
  omit?: Prisma.training_menusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.training_menusInclude<ExtArgs> | null
  /**
   * The data needed to create a training_menus.
   */
  data?: Prisma.XOR<Prisma.training_menusCreateInput, Prisma.training_menusUncheckedCreateInput>
}

/**
 * training_menus createMany
 */
export type training_menusCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many training_menus.
   */
  data: Prisma.training_menusCreateManyInput | Prisma.training_menusCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * training_menus createManyAndReturn
 */
export type training_menusCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the training_menus
   */
  select?: Prisma.training_menusSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the training_menus
   */
  omit?: Prisma.training_menusOmit<ExtArgs> | null
  /**
   * The data used to create many training_menus.
   */
  data: Prisma.training_menusCreateManyInput | Prisma.training_menusCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * training_menus update
 */
export type training_menusUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the training_menus
   */
  select?: Prisma.training_menusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the training_menus
   */
  omit?: Prisma.training_menusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.training_menusInclude<ExtArgs> | null
  /**
   * The data needed to update a training_menus.
   */
  data: Prisma.XOR<Prisma.training_menusUpdateInput, Prisma.training_menusUncheckedUpdateInput>
  /**
   * Choose, which training_menus to update.
   */
  where: Prisma.training_menusWhereUniqueInput
}

/**
 * training_menus updateMany
 */
export type training_menusUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update training_menus.
   */
  data: Prisma.XOR<Prisma.training_menusUpdateManyMutationInput, Prisma.training_menusUncheckedUpdateManyInput>
  /**
   * Filter which training_menus to update
   */
  where?: Prisma.training_menusWhereInput
  /**
   * Limit how many training_menus to update.
   */
  limit?: number
}

/**
 * training_menus updateManyAndReturn
 */
export type training_menusUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the training_menus
   */
  select?: Prisma.training_menusSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the training_menus
   */
  omit?: Prisma.training_menusOmit<ExtArgs> | null
  /**
   * The data used to update training_menus.
   */
  data: Prisma.XOR<Prisma.training_menusUpdateManyMutationInput, Prisma.training_menusUncheckedUpdateManyInput>
  /**
   * Filter which training_menus to update
   */
  where?: Prisma.training_menusWhereInput
  /**
   * Limit how many training_menus to update.
   */
  limit?: number
}

/**
 * training_menus upsert
 */
export type training_menusUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the training_menus
   */
  select?: Prisma.training_menusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the training_menus
   */
  omit?: Prisma.training_menusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.training_menusInclude<ExtArgs> | null
  /**
   * The filter to search for the training_menus to update in case it exists.
   */
  where: Prisma.training_menusWhereUniqueInput
  /**
   * In case the training_menus found by the `where` argument doesn't exist, create a new training_menus with this data.
   */
  create: Prisma.XOR<Prisma.training_menusCreateInput, Prisma.training_menusUncheckedCreateInput>
  /**
   * In case the training_menus was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.training_menusUpdateInput, Prisma.training_menusUncheckedUpdateInput>
}

/**
 * training_menus delete
 */
export type training_menusDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the training_menus
   */
  select?: Prisma.training_menusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the training_menus
   */
  omit?: Prisma.training_menusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.training_menusInclude<ExtArgs> | null
  /**
   * Filter which training_menus to delete.
   */
  where: Prisma.training_menusWhereUniqueInput
}

/**
 * training_menus deleteMany
 */
export type training_menusDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which training_menus to delete
   */
  where?: Prisma.training_menusWhereInput
  /**
   * Limit how many training_menus to delete.
   */
  limit?: number
}

/**
 * training_menus.user_recaps
 */
export type training_menus$user_recapsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the user_recaps
   */
  select?: Prisma.user_recapsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the user_recaps
   */
  omit?: Prisma.user_recapsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.user_recapsInclude<ExtArgs> | null
  where?: Prisma.user_recapsWhereInput
  orderBy?: Prisma.user_recapsOrderByWithRelationInput | Prisma.user_recapsOrderByWithRelationInput[]
  cursor?: Prisma.user_recapsWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.User_recapsScalarFieldEnum | Prisma.User_recapsScalarFieldEnum[]
}

/**
 * training_menus without action
 */
export type training_menusDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the training_menus
   */
  select?: Prisma.training_menusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the training_menus
   */
  omit?: Prisma.training_menusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.training_menusInclude<ExtArgs> | null
}
