
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `user_recaps` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model user_recaps
 * 
 */
export type user_recapsModel = runtime.Types.Result.DefaultSelection<Prisma.$user_recapsPayload>

export type AggregateUser_recaps = {
  _count: User_recapsCountAggregateOutputType | null
  _avg: User_recapsAvgAggregateOutputType | null
  _sum: User_recapsSumAggregateOutputType | null
  _min: User_recapsMinAggregateOutputType | null
  _max: User_recapsMaxAggregateOutputType | null
}

export type User_recapsAvgAggregateOutputType = {
  id: number | null
  menu_id: number | null
}

export type User_recapsSumAggregateOutputType = {
  id: number | null
  menu_id: number | null
}

export type User_recapsMinAggregateOutputType = {
  id: number | null
  menu_id: number | null
  completed_at: Date | null
}

export type User_recapsMaxAggregateOutputType = {
  id: number | null
  menu_id: number | null
  completed_at: Date | null
}

export type User_recapsCountAggregateOutputType = {
  id: number
  menu_id: number
  summary: number
  completed_at: number
  _all: number
}


export type User_recapsAvgAggregateInputType = {
  id?: true
  menu_id?: true
}

export type User_recapsSumAggregateInputType = {
  id?: true
  menu_id?: true
}

export type User_recapsMinAggregateInputType = {
  id?: true
  menu_id?: true
  completed_at?: true
}

export type User_recapsMaxAggregateInputType = {
  id?: true
  menu_id?: true
  completed_at?: true
}

export type User_recapsCountAggregateInputType = {
  id?: true
  menu_id?: true
  summary?: true
  completed_at?: true
  _all?: true
}

export type User_recapsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which user_recaps to aggregate.
   */
  where?: Prisma.user_recapsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of user_recaps to fetch.
   */
  orderBy?: Prisma.user_recapsOrderByWithRelationInput | Prisma.user_recapsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.user_recapsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` user_recaps from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` user_recaps.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned user_recaps
  **/
  _count?: true | User_recapsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: User_recapsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: User_recapsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: User_recapsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: User_recapsMaxAggregateInputType
}

export type GetUser_recapsAggregateType<T extends User_recapsAggregateArgs> = {
      [P in keyof T & keyof AggregateUser_recaps]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateUser_recaps[P]>
    : Prisma.GetScalarType<T[P], AggregateUser_recaps[P]>
}




export type user_recapsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.user_recapsWhereInput
  orderBy?: Prisma.user_recapsOrderByWithAggregationInput | Prisma.user_recapsOrderByWithAggregationInput[]
  by: Prisma.User_recapsScalarFieldEnum[] | Prisma.User_recapsScalarFieldEnum
  having?: Prisma.user_recapsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: User_recapsCountAggregateInputType | true
  _avg?: User_recapsAvgAggregateInputType
  _sum?: User_recapsSumAggregateInputType
  _min?: User_recapsMinAggregateInputType
  _max?: User_recapsMaxAggregateInputType
}

export type User_recapsGroupByOutputType = {
  id: number
  menu_id: number | null
  summary: runtime.JsonValue | null
  completed_at: Date | null
  _count: User_recapsCountAggregateOutputType | null
  _avg: User_recapsAvgAggregateOutputType | null
  _sum: User_recapsSumAggregateOutputType | null
  _min: User_recapsMinAggregateOutputType | null
  _max: User_recapsMaxAggregateOutputType | null
}

type GetUser_recapsGroupByPayload<T extends user_recapsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<User_recapsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof User_recapsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], User_recapsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], User_recapsGroupByOutputType[P]>
      }
    >
  >



export type user_recapsWhereInput = {
  AND?: Prisma.user_recapsWhereInput | Prisma.user_recapsWhereInput[]
  OR?: Prisma.user_recapsWhereInput[]
  NOT?: Prisma.user_recapsWhereInput | Prisma.user_recapsWhereInput[]
  id?: Prisma.IntFilter<"user_recaps"> | number
  menu_id?: Prisma.IntNullableFilter<"user_recaps"> | number | null
  summary?: Prisma.JsonNullableFilter<"user_recaps">
  completed_at?: Prisma.DateTimeNullableFilter<"user_recaps"> | Date | string | null
  training_menus?: Prisma.XOR<Prisma.Training_menusNullableScalarRelationFilter, Prisma.training_menusWhereInput> | null
}

export type user_recapsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  menu_id?: Prisma.SortOrderInput | Prisma.SortOrder
  summary?: Prisma.SortOrderInput | Prisma.SortOrder
  completed_at?: Prisma.SortOrderInput | Prisma.SortOrder
  training_menus?: Prisma.training_menusOrderByWithRelationInput
}

export type user_recapsWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.user_recapsWhereInput | Prisma.user_recapsWhereInput[]
  OR?: Prisma.user_recapsWhereInput[]
  NOT?: Prisma.user_recapsWhereInput | Prisma.user_recapsWhereInput[]
  menu_id?: Prisma.IntNullableFilter<"user_recaps"> | number | null
  summary?: Prisma.JsonNullableFilter<"user_recaps">
  completed_at?: Prisma.DateTimeNullableFilter<"user_recaps"> | Date | string | null
  training_menus?: Prisma.XOR<Prisma.Training_menusNullableScalarRelationFilter, Prisma.training_menusWhereInput> | null
}, "id">

export type user_recapsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  menu_id?: Prisma.SortOrderInput | Prisma.SortOrder
  summary?: Prisma.SortOrderInput | Prisma.SortOrder
  completed_at?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.user_recapsCountOrderByAggregateInput
  _avg?: Prisma.user_recapsAvgOrderByAggregateInput
  _max?: Prisma.user_recapsMaxOrderByAggregateInput
  _min?: Prisma.user_recapsMinOrderByAggregateInput
  _sum?: Prisma.user_recapsSumOrderByAggregateInput
}

export type user_recapsScalarWhereWithAggregatesInput = {
  AND?: Prisma.user_recapsScalarWhereWithAggregatesInput | Prisma.user_recapsScalarWhereWithAggregatesInput[]
  OR?: Prisma.user_recapsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.user_recapsScalarWhereWithAggregatesInput | Prisma.user_recapsScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"user_recaps"> | number
  menu_id?: Prisma.IntNullableWithAggregatesFilter<"user_recaps"> | number | null
  summary?: Prisma.JsonNullableWithAggregatesFilter<"user_recaps">
  completed_at?: Prisma.DateTimeNullableWithAggregatesFilter<"user_recaps"> | Date | string | null
}

export type user_recapsCreateInput = {
  summary?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  completed_at?: Date | string | null
  training_menus?: Prisma.training_menusCreateNestedOneWithoutUser_recapsInput
}

export type user_recapsUncheckedCreateInput = {
  id?: number
  menu_id?: number | null
  summary?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  completed_at?: Date | string | null
}

export type user_recapsUpdateInput = {
  summary?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  completed_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  training_menus?: Prisma.training_menusUpdateOneWithoutUser_recapsNestedInput
}

export type user_recapsUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  menu_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  summary?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  completed_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type user_recapsCreateManyInput = {
  id?: number
  menu_id?: number | null
  summary?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  completed_at?: Date | string | null
}

export type user_recapsUpdateManyMutationInput = {
  summary?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  completed_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type user_recapsUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  menu_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  summary?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  completed_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type User_recapsListRelationFilter = {
  every?: Prisma.user_recapsWhereInput
  some?: Prisma.user_recapsWhereInput
  none?: Prisma.user_recapsWhereInput
}

export type user_recapsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type user_recapsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  menu_id?: Prisma.SortOrder
  summary?: Prisma.SortOrder
  completed_at?: Prisma.SortOrder
}

export type user_recapsAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  menu_id?: Prisma.SortOrder
}

export type user_recapsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  menu_id?: Prisma.SortOrder
  completed_at?: Prisma.SortOrder
}

export type user_recapsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  menu_id?: Prisma.SortOrder
  completed_at?: Prisma.SortOrder
}

export type user_recapsSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  menu_id?: Prisma.SortOrder
}

export type user_recapsCreateNestedManyWithoutTraining_menusInput = {
  create?: Prisma.XOR<Prisma.user_recapsCreateWithoutTraining_menusInput, Prisma.user_recapsUncheckedCreateWithoutTraining_menusInput> | Prisma.user_recapsCreateWithoutTraining_menusInput[] | Prisma.user_recapsUncheckedCreateWithoutTraining_menusInput[]
  connectOrCreate?: Prisma.user_recapsCreateOrConnectWithoutTraining_menusInput | Prisma.user_recapsCreateOrConnectWithoutTraining_menusInput[]
  createMany?: Prisma.user_recapsCreateManyTraining_menusInputEnvelope
  connect?: Prisma.user_recapsWhereUniqueInput | Prisma.user_recapsWhereUniqueInput[]
}

export type user_recapsUncheckedCreateNestedManyWithoutTraining_menusInput = {
  create?: Prisma.XOR<Prisma.user_recapsCreateWithoutTraining_menusInput, Prisma.user_recapsUncheckedCreateWithoutTraining_menusInput> | Prisma.user_recapsCreateWithoutTraining_menusInput[] | Prisma.user_recapsUncheckedCreateWithoutTraining_menusInput[]
  connectOrCreate?: Prisma.user_recapsCreateOrConnectWithoutTraining_menusInput | Prisma.user_recapsCreateOrConnectWithoutTraining_menusInput[]
  createMany?: Prisma.user_recapsCreateManyTraining_menusInputEnvelope
  connect?: Prisma.user_recapsWhereUniqueInput | Prisma.user_recapsWhereUniqueInput[]
}

export type user_recapsUpdateManyWithoutTraining_menusNestedInput = {
  create?: Prisma.XOR<Prisma.user_recapsCreateWithoutTraining_menusInput, Prisma.user_recapsUncheckedCreateWithoutTraining_menusInput> | Prisma.user_recapsCreateWithoutTraining_menusInput[] | Prisma.user_recapsUncheckedCreateWithoutTraining_menusInput[]
  connectOrCreate?: Prisma.user_recapsCreateOrConnectWithoutTraining_menusInput | Prisma.user_recapsCreateOrConnectWithoutTraining_menusInput[]
  upsert?: Prisma.user_recapsUpsertWithWhereUniqueWithoutTraining_menusInput | Prisma.user_recapsUpsertWithWhereUniqueWithoutTraining_menusInput[]
  createMany?: Prisma.user_recapsCreateManyTraining_menusInputEnvelope
  set?: Prisma.user_recapsWhereUniqueInput | Prisma.user_recapsWhereUniqueInput[]
  disconnect?: Prisma.user_recapsWhereUniqueInput | Prisma.user_recapsWhereUniqueInput[]
  delete?: Prisma.user_recapsWhereUniqueInput | Prisma.user_recapsWhereUniqueInput[]
  connect?: Prisma.user_recapsWhereUniqueInput | Prisma.user_recapsWhereUniqueInput[]
  update?: Prisma.user_recapsUpdateWithWhereUniqueWithoutTraining_menusInput | Prisma.user_recapsUpdateWithWhereUniqueWithoutTraining_menusInput[]
  updateMany?: Prisma.user_recapsUpdateManyWithWhereWithoutTraining_menusInput | Prisma.user_recapsUpdateManyWithWhereWithoutTraining_menusInput[]
  deleteMany?: Prisma.user_recapsScalarWhereInput | Prisma.user_recapsScalarWhereInput[]
}

export type user_recapsUncheckedUpdateManyWithoutTraining_menusNestedInput = {
  create?: Prisma.XOR<Prisma.user_recapsCreateWithoutTraining_menusInput, Prisma.user_recapsUncheckedCreateWithoutTraining_menusInput> | Prisma.user_recapsCreateWithoutTraining_menusInput[] | Prisma.user_recapsUncheckedCreateWithoutTraining_menusInput[]
  connectOrCreate?: Prisma.user_recapsCreateOrConnectWithoutTraining_menusInput | Prisma.user_recapsCreateOrConnectWithoutTraining_menusInput[]
  upsert?: Prisma.user_recapsUpsertWithWhereUniqueWithoutTraining_menusInput | Prisma.user_recapsUpsertWithWhereUniqueWithoutTraining_menusInput[]
  createMany?: Prisma.user_recapsCreateManyTraining_menusInputEnvelope
  set?: Prisma.user_recapsWhereUniqueInput | Prisma.user_recapsWhereUniqueInput[]
  disconnect?: Prisma.user_recapsWhereUniqueInput | Prisma.user_recapsWhereUniqueInput[]
  delete?: Prisma.user_recapsWhereUniqueInput | Prisma.user_recapsWhereUniqueInput[]
  connect?: Prisma.user_recapsWhereUniqueInput | Prisma.user_recapsWhereUniqueInput[]
  update?: Prisma.user_recapsUpdateWithWhereUniqueWithoutTraining_menusInput | Prisma.user_recapsUpdateWithWhereUniqueWithoutTraining_menusInput[]
  updateMany?: Prisma.user_recapsUpdateManyWithWhereWithoutTraining_menusInput | Prisma.user_recapsUpdateManyWithWhereWithoutTraining_menusInput[]
  deleteMany?: Prisma.user_recapsScalarWhereInput | Prisma.user_recapsScalarWhereInput[]
}

export type NullableIntFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type user_recapsCreateWithoutTraining_menusInput = {
  summary?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  completed_at?: Date | string | null
}

export type user_recapsUncheckedCreateWithoutTraining_menusInput = {
  id?: number
  summary?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  completed_at?: Date | string | null
}

export type user_recapsCreateOrConnectWithoutTraining_menusInput = {
  where: Prisma.user_recapsWhereUniqueInput
  create: Prisma.XOR<Prisma.user_recapsCreateWithoutTraining_menusInput, Prisma.user_recapsUncheckedCreateWithoutTraining_menusInput>
}

export type user_recapsCreateManyTraining_menusInputEnvelope = {
  data: Prisma.user_recapsCreateManyTraining_menusInput | Prisma.user_recapsCreateManyTraining_menusInput[]
  skipDuplicates?: boolean
}

export type user_recapsUpsertWithWhereUniqueWithoutTraining_menusInput = {
  where: Prisma.user_recapsWhereUniqueInput
  update: Prisma.XOR<Prisma.user_recapsUpdateWithoutTraining_menusInput, Prisma.user_recapsUncheckedUpdateWithoutTraining_menusInput>
  create: Prisma.XOR<Prisma.user_recapsCreateWithoutTraining_menusInput, Prisma.user_recapsUncheckedCreateWithoutTraining_menusInput>
}

export type user_recapsUpdateWithWhereUniqueWithoutTraining_menusInput = {
  where: Prisma.user_recapsWhereUniqueInput
  data: Prisma.XOR<Prisma.user_recapsUpdateWithoutTraining_menusInput, Prisma.user_recapsUncheckedUpdateWithoutTraining_menusInput>
}

export type user_recapsUpdateManyWithWhereWithoutTraining_menusInput = {
  where: Prisma.user_recapsScalarWhereInput
  data: Prisma.XOR<Prisma.user_recapsUpdateManyMutationInput, Prisma.user_recapsUncheckedUpdateManyWithoutTraining_menusInput>
}

export type user_recapsScalarWhereInput = {
  AND?: Prisma.user_recapsScalarWhereInput | Prisma.user_recapsScalarWhereInput[]
  OR?: Prisma.user_recapsScalarWhereInput[]
  NOT?: Prisma.user_recapsScalarWhereInput | Prisma.user_recapsScalarWhereInput[]
  id?: Prisma.IntFilter<"user_recaps"> | number
  menu_id?: Prisma.IntNullableFilter<"user_recaps"> | number | null
  summary?: Prisma.JsonNullableFilter<"user_recaps">
  completed_at?: Prisma.DateTimeNullableFilter<"user_recaps"> | Date | string | null
}

export type user_recapsCreateManyTraining_menusInput = {
  id?: number
  summary?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  completed_at?: Date | string | null
}

export type user_recapsUpdateWithoutTraining_menusInput = {
  summary?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  completed_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type user_recapsUncheckedUpdateWithoutTraining_menusInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  summary?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  completed_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type user_recapsUncheckedUpdateManyWithoutTraining_menusInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  summary?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  completed_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}



export type user_recapsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  menu_id?: boolean
  summary?: boolean
  completed_at?: boolean
  training_menus?: boolean | Prisma.user_recaps$training_menusArgs<ExtArgs>
}, ExtArgs["result"]["user_recaps"]>

export type user_recapsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  menu_id?: boolean
  summary?: boolean
  completed_at?: boolean
  training_menus?: boolean | Prisma.user_recaps$training_menusArgs<ExtArgs>
}, ExtArgs["result"]["user_recaps"]>

export type user_recapsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  menu_id?: boolean
  summary?: boolean
  completed_at?: boolean
  training_menus?: boolean | Prisma.user_recaps$training_menusArgs<ExtArgs>
}, ExtArgs["result"]["user_recaps"]>

export type user_recapsSelectScalar = {
  id?: boolean
  menu_id?: boolean
  summary?: boolean
  completed_at?: boolean
}

export type user_recapsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "menu_id" | "summary" | "completed_at", ExtArgs["result"]["user_recaps"]>
export type user_recapsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  training_menus?: boolean | Prisma.user_recaps$training_menusArgs<ExtArgs>
}
export type user_recapsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  training_menus?: boolean | Prisma.user_recaps$training_menusArgs<ExtArgs>
}
export type user_recapsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  training_menus?: boolean | Prisma.user_recaps$training_menusArgs<ExtArgs>
}

export type $user_recapsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "user_recaps"
  objects: {
    training_menus: Prisma.$training_menusPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    menu_id: number | null
    summary: runtime.JsonValue | null
    completed_at: Date | null
  }, ExtArgs["result"]["user_recaps"]>
  composites: {}
}

export type user_recapsGetPayload<S extends boolean | null | undefined | user_recapsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$user_recapsPayload, S>

export type user_recapsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<user_recapsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: User_recapsCountAggregateInputType | true
  }

export interface user_recapsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['user_recaps'], meta: { name: 'user_recaps' } }
  /**
   * Find zero or one User_recaps that matches the filter.
   * @param {user_recapsFindUniqueArgs} args - Arguments to find a User_recaps
   * @example
   * // Get one User_recaps
   * const user_recaps = await prisma.user_recaps.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends user_recapsFindUniqueArgs>(args: Prisma.SelectSubset<T, user_recapsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__user_recapsClient<runtime.Types.Result.GetResult<Prisma.$user_recapsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one User_recaps that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {user_recapsFindUniqueOrThrowArgs} args - Arguments to find a User_recaps
   * @example
   * // Get one User_recaps
   * const user_recaps = await prisma.user_recaps.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends user_recapsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, user_recapsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__user_recapsClient<runtime.Types.Result.GetResult<Prisma.$user_recapsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first User_recaps that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {user_recapsFindFirstArgs} args - Arguments to find a User_recaps
   * @example
   * // Get one User_recaps
   * const user_recaps = await prisma.user_recaps.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends user_recapsFindFirstArgs>(args?: Prisma.SelectSubset<T, user_recapsFindFirstArgs<ExtArgs>>): Prisma.Prisma__user_recapsClient<runtime.Types.Result.GetResult<Prisma.$user_recapsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first User_recaps that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {user_recapsFindFirstOrThrowArgs} args - Arguments to find a User_recaps
   * @example
   * // Get one User_recaps
   * const user_recaps = await prisma.user_recaps.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends user_recapsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, user_recapsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__user_recapsClient<runtime.Types.Result.GetResult<Prisma.$user_recapsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more User_recaps that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {user_recapsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all User_recaps
   * const user_recaps = await prisma.user_recaps.findMany()
   * 
   * // Get first 10 User_recaps
   * const user_recaps = await prisma.user_recaps.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const user_recapsWithIdOnly = await prisma.user_recaps.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends user_recapsFindManyArgs>(args?: Prisma.SelectSubset<T, user_recapsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$user_recapsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a User_recaps.
   * @param {user_recapsCreateArgs} args - Arguments to create a User_recaps.
   * @example
   * // Create one User_recaps
   * const User_recaps = await prisma.user_recaps.create({
   *   data: {
   *     // ... data to create a User_recaps
   *   }
   * })
   * 
   */
  create<T extends user_recapsCreateArgs>(args: Prisma.SelectSubset<T, user_recapsCreateArgs<ExtArgs>>): Prisma.Prisma__user_recapsClient<runtime.Types.Result.GetResult<Prisma.$user_recapsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many User_recaps.
   * @param {user_recapsCreateManyArgs} args - Arguments to create many User_recaps.
   * @example
   * // Create many User_recaps
   * const user_recaps = await prisma.user_recaps.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends user_recapsCreateManyArgs>(args?: Prisma.SelectSubset<T, user_recapsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many User_recaps and returns the data saved in the database.
   * @param {user_recapsCreateManyAndReturnArgs} args - Arguments to create many User_recaps.
   * @example
   * // Create many User_recaps
   * const user_recaps = await prisma.user_recaps.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many User_recaps and only return the `id`
   * const user_recapsWithIdOnly = await prisma.user_recaps.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends user_recapsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, user_recapsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$user_recapsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a User_recaps.
   * @param {user_recapsDeleteArgs} args - Arguments to delete one User_recaps.
   * @example
   * // Delete one User_recaps
   * const User_recaps = await prisma.user_recaps.delete({
   *   where: {
   *     // ... filter to delete one User_recaps
   *   }
   * })
   * 
   */
  delete<T extends user_recapsDeleteArgs>(args: Prisma.SelectSubset<T, user_recapsDeleteArgs<ExtArgs>>): Prisma.Prisma__user_recapsClient<runtime.Types.Result.GetResult<Prisma.$user_recapsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one User_recaps.
   * @param {user_recapsUpdateArgs} args - Arguments to update one User_recaps.
   * @example
   * // Update one User_recaps
   * const user_recaps = await prisma.user_recaps.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends user_recapsUpdateArgs>(args: Prisma.SelectSubset<T, user_recapsUpdateArgs<ExtArgs>>): Prisma.Prisma__user_recapsClient<runtime.Types.Result.GetResult<Prisma.$user_recapsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more User_recaps.
   * @param {user_recapsDeleteManyArgs} args - Arguments to filter User_recaps to delete.
   * @example
   * // Delete a few User_recaps
   * const { count } = await prisma.user_recaps.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends user_recapsDeleteManyArgs>(args?: Prisma.SelectSubset<T, user_recapsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more User_recaps.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {user_recapsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many User_recaps
   * const user_recaps = await prisma.user_recaps.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends user_recapsUpdateManyArgs>(args: Prisma.SelectSubset<T, user_recapsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more User_recaps and returns the data updated in the database.
   * @param {user_recapsUpdateManyAndReturnArgs} args - Arguments to update many User_recaps.
   * @example
   * // Update many User_recaps
   * const user_recaps = await prisma.user_recaps.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more User_recaps and only return the `id`
   * const user_recapsWithIdOnly = await prisma.user_recaps.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends user_recapsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, user_recapsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$user_recapsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one User_recaps.
   * @param {user_recapsUpsertArgs} args - Arguments to update or create a User_recaps.
   * @example
   * // Update or create a User_recaps
   * const user_recaps = await prisma.user_recaps.upsert({
   *   create: {
   *     // ... data to create a User_recaps
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the User_recaps we want to update
   *   }
   * })
   */
  upsert<T extends user_recapsUpsertArgs>(args: Prisma.SelectSubset<T, user_recapsUpsertArgs<ExtArgs>>): Prisma.Prisma__user_recapsClient<runtime.Types.Result.GetResult<Prisma.$user_recapsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of User_recaps.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {user_recapsCountArgs} args - Arguments to filter User_recaps to count.
   * @example
   * // Count the number of User_recaps
   * const count = await prisma.user_recaps.count({
   *   where: {
   *     // ... the filter for the User_recaps we want to count
   *   }
   * })
  **/
  count<T extends user_recapsCountArgs>(
    args?: Prisma.Subset<T, user_recapsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], User_recapsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a User_recaps.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {User_recapsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends User_recapsAggregateArgs>(args: Prisma.Subset<T, User_recapsAggregateArgs>): Prisma.PrismaPromise<GetUser_recapsAggregateType<T>>

  /**
   * Group by User_recaps.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {user_recapsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends user_recapsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: user_recapsGroupByArgs['orderBy'] }
      : { orderBy?: user_recapsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, user_recapsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetUser_recapsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the user_recaps model
 */
readonly fields: user_recapsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for user_recaps.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__user_recapsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  training_menus<T extends Prisma.user_recaps$training_menusArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.user_recaps$training_menusArgs<ExtArgs>>): Prisma.Prisma__training_menusClient<runtime.Types.Result.GetResult<Prisma.$training_menusPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the user_recaps model
 */
export interface user_recapsFieldRefs {
  readonly id: Prisma.FieldRef<"user_recaps", 'Int'>
  readonly menu_id: Prisma.FieldRef<"user_recaps", 'Int'>
  readonly summary: Prisma.FieldRef<"user_recaps", 'Json'>
  readonly completed_at: Prisma.FieldRef<"user_recaps", 'DateTime'>
}
    

// Custom InputTypes
/**
 * user_recaps findUnique
 */
export type user_recapsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the user_recaps
   */
  select?: Prisma.user_recapsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the user_recaps
   */
  omit?: Prisma.user_recapsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.user_recapsInclude<ExtArgs> | null
  /**
   * Filter, which user_recaps to fetch.
   */
  where: Prisma.user_recapsWhereUniqueInput
}

/**
 * user_recaps findUniqueOrThrow
 */
export type user_recapsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the user_recaps
   */
  select?: Prisma.user_recapsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the user_recaps
   */
  omit?: Prisma.user_recapsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.user_recapsInclude<ExtArgs> | null
  /**
   * Filter, which user_recaps to fetch.
   */
  where: Prisma.user_recapsWhereUniqueInput
}

/**
 * user_recaps findFirst
 */
export type user_recapsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the user_recaps
   */
  select?: Prisma.user_recapsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the user_recaps
   */
  omit?: Prisma.user_recapsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.user_recapsInclude<ExtArgs> | null
  /**
   * Filter, which user_recaps to fetch.
   */
  where?: Prisma.user_recapsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of user_recaps to fetch.
   */
  orderBy?: Prisma.user_recapsOrderByWithRelationInput | Prisma.user_recapsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for user_recaps.
   */
  cursor?: Prisma.user_recapsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` user_recaps from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` user_recaps.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of user_recaps.
   */
  distinct?: Prisma.User_recapsScalarFieldEnum | Prisma.User_recapsScalarFieldEnum[]
}

/**
 * user_recaps findFirstOrThrow
 */
export type user_recapsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the user_recaps
   */
  select?: Prisma.user_recapsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the user_recaps
   */
  omit?: Prisma.user_recapsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.user_recapsInclude<ExtArgs> | null
  /**
   * Filter, which user_recaps to fetch.
   */
  where?: Prisma.user_recapsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of user_recaps to fetch.
   */
  orderBy?: Prisma.user_recapsOrderByWithRelationInput | Prisma.user_recapsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for user_recaps.
   */
  cursor?: Prisma.user_recapsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` user_recaps from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` user_recaps.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of user_recaps.
   */
  distinct?: Prisma.User_recapsScalarFieldEnum | Prisma.User_recapsScalarFieldEnum[]
}

/**
 * user_recaps findMany
 */
export type user_recapsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the user_recaps
   */
  select?: Prisma.user_recapsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the user_recaps
   */
  omit?: Prisma.user_recapsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.user_recapsInclude<ExtArgs> | null
  /**
   * Filter, which user_recaps to fetch.
   */
  where?: Prisma.user_recapsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of user_recaps to fetch.
   */
  orderBy?: Prisma.user_recapsOrderByWithRelationInput | Prisma.user_recapsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing user_recaps.
   */
  cursor?: Prisma.user_recapsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` user_recaps from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` user_recaps.
   */
  skip?: number
  distinct?: Prisma.User_recapsScalarFieldEnum | Prisma.User_recapsScalarFieldEnum[]
}

/**
 * user_recaps create
 */
export type user_recapsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the user_recaps
   */
  select?: Prisma.user_recapsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the user_recaps
   */
  omit?: Prisma.user_recapsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.user_recapsInclude<ExtArgs> | null
  /**
   * The data needed to create a user_recaps.
   */
  data?: Prisma.XOR<Prisma.user_recapsCreateInput, Prisma.user_recapsUncheckedCreateInput>
}

/**
 * user_recaps createMany
 */
export type user_recapsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many user_recaps.
   */
  data: Prisma.user_recapsCreateManyInput | Prisma.user_recapsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * user_recaps createManyAndReturn
 */
export type user_recapsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the user_recaps
   */
  select?: Prisma.user_recapsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the user_recaps
   */
  omit?: Prisma.user_recapsOmit<ExtArgs> | null
  /**
   * The data used to create many user_recaps.
   */
  data: Prisma.user_recapsCreateManyInput | Prisma.user_recapsCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.user_recapsIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * user_recaps update
 */
export type user_recapsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the user_recaps
   */
  select?: Prisma.user_recapsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the user_recaps
   */
  omit?: Prisma.user_recapsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.user_recapsInclude<ExtArgs> | null
  /**
   * The data needed to update a user_recaps.
   */
  data: Prisma.XOR<Prisma.user_recapsUpdateInput, Prisma.user_recapsUncheckedUpdateInput>
  /**
   * Choose, which user_recaps to update.
   */
  where: Prisma.user_recapsWhereUniqueInput
}

/**
 * user_recaps updateMany
 */
export type user_recapsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update user_recaps.
   */
  data: Prisma.XOR<Prisma.user_recapsUpdateManyMutationInput, Prisma.user_recapsUncheckedUpdateManyInput>
  /**
   * Filter which user_recaps to update
   */
  where?: Prisma.user_recapsWhereInput
  /**
   * Limit how many user_recaps to update.
   */
  limit?: number
}

/**
 * user_recaps updateManyAndReturn
 */
export type user_recapsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the user_recaps
   */
  select?: Prisma.user_recapsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the user_recaps
   */
  omit?: Prisma.user_recapsOmit<ExtArgs> | null
  /**
   * The data used to update user_recaps.
   */
  data: Prisma.XOR<Prisma.user_recapsUpdateManyMutationInput, Prisma.user_recapsUncheckedUpdateManyInput>
  /**
   * Filter which user_recaps to update
   */
  where?: Prisma.user_recapsWhereInput
  /**
   * Limit how many user_recaps to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.user_recapsIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * user_recaps upsert
 */
export type user_recapsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the user_recaps
   */
  select?: Prisma.user_recapsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the user_recaps
   */
  omit?: Prisma.user_recapsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.user_recapsInclude<ExtArgs> | null
  /**
   * The filter to search for the user_recaps to update in case it exists.
   */
  where: Prisma.user_recapsWhereUniqueInput
  /**
   * In case the user_recaps found by the `where` argument doesn't exist, create a new user_recaps with this data.
   */
  create: Prisma.XOR<Prisma.user_recapsCreateInput, Prisma.user_recapsUncheckedCreateInput>
  /**
   * In case the user_recaps was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.user_recapsUpdateInput, Prisma.user_recapsUncheckedUpdateInput>
}

/**
 * user_recaps delete
 */
export type user_recapsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the user_recaps
   */
  select?: Prisma.user_recapsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the user_recaps
   */
  omit?: Prisma.user_recapsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.user_recapsInclude<ExtArgs> | null
  /**
   * Filter which user_recaps to delete.
   */
  where: Prisma.user_recapsWhereUniqueInput
}

/**
 * user_recaps deleteMany
 */
export type user_recapsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which user_recaps to delete
   */
  where?: Prisma.user_recapsWhereInput
  /**
   * Limit how many user_recaps to delete.
   */
  limit?: number
}

/**
 * user_recaps.training_menus
 */
export type user_recaps$training_menusArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the training_menus
   */
  select?: Prisma.training_menusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the training_menus
   */
  omit?: Prisma.training_menusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.training_menusInclude<ExtArgs> | null
  where?: Prisma.training_menusWhereInput
}

/**
 * user_recaps without action
 */
export type user_recapsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the user_recaps
   */
  select?: Prisma.user_recapsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the user_recaps
   */
  omit?: Prisma.user_recapsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.user_recapsInclude<ExtArgs> | null
}
